# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - dev-checkpoint
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Check for exisiting directory
        run: "(test -d ~/remix_gun && rm -rf ~/remix_gun) || echo app does not exist, skipping step"

      - name: Clone Repository
        run: |
          git clone https://github.com/bresnow/remix.gun-react-18-streaming ~/remix_gun
          cd ~/remix_gun

  docker:
    runs-on: self-hosted

    steps:
      - name: Build Docker Image & Push to Registry
        env:
          VERSION: 0.2.0

        run: |
          docker build -t bresnow/rmx-gun:${{ env.VERSION }} .
          docker push bresnow/rmx-gun:${{ env.VERSION }}

      - name: Deploy Docker Swarm Script
        env:
          VERSION: 0.2.0
        run: |
          export VERSION=${{ env.VERSION }}
          docker service update rmx-gun_fltngmmth --image=bresnow/rmx-gun:${{ env.VERSION }}
          docker service update rmx-gun_peer --image=bresnow/rmx-gun:${{ env.VERSION }}
      - name: "Logs"
        run: |
          docker service logs rmx-gun_fltngmmth
      #          # docker stack rm rmx-gun
      - name: Clean Up
        run: |
          rm -rf ~/remix_gun
